### ISSUE TITLE
enh: Change the default value of `debug` to a FALSE-like sentinel value

### ISSUE THREAD

**Issue by schloerke** [rstudio/plumber#962]
There are multiple reports of confusion around `debug` and the default error handler. 
* Errors are displayed locally when `interactive()`
* Errors are not displayed when deployed

Default `debug` value:
https://github.com/rstudio/plumber/blob/7f51e24bb6e6050c7743ed6c98015ecf42b50527/R/plumber.R#L1338-L1340

## Proposal

Change the default value of `debug` to behave like a `FALSE` value. 

To maintain least surprise (default to same locally, display a message with instructions on how to turn in on:
```r
Error reporting has been turned off by default. See `pr_set_debug` for more details. 
To disable this message, setting a debug value.
```

## Tasks

- [ ] Change the default value of `debug` to behave like a `FALSE` value. 
- [ ] Add `rlang::inform(.frequency="once", .frequency_id="pr_set_debug_message")` message. 
	- This should only be displayed if `rlang::is_interactive()` is `TRUE`.
- [ ] Add `#* @plumber` example within `pr_set_debug()` docs to show to to set the value within a plumbed file
- [ ] News entry of changed behavior

**Comment by thomasp85** [comment]
Would `NA` or `NULL` not be sufficient sentinels along with the proposed message. These are standard sentinels for capturing lack of user action
